name: check-tex

on:
  pull_request:
    branches: main
    paths: [docs/**]

permissions:
  contents: write

jobs:
  check-tex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: xu-cheng/texlive-action@v3
        name: Compile LaTeX Files
        with:
          scheme: full
          texlive_version: 2025
          run: |
            apk add make
            cd docs
            make -B
      - name: Collect all PDFs
        run: |
          mapfile -t ALL_PDFS < <(find . -type f -name '*.pdf' || true)
          mkdir -p all_pdfs_dir
          for f in "${ALL_PDFS[@]}"; do
            if [ -f "$f" ]; then
              mkdir -p "$(dirname "all_pdfs_dir/$f")"
              cp "$f" "all_pdfs_dir/$f"
            fi
          done
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: all-pdfs
          path: all_pdfs_dir
          if-no-files-found: ignore
      - name: Reset unstaged changes
        run: |
          git restore .
      - uses: xu-cheng/texlive-action@v3
        name: Format LaTeX Files
        with:
          scheme: full
          texlive_version: 2025
          run: |
            cd docs
            find . -type f -name '*.tex' -print0 | xargs -0 -n 1 latexindent "-y=defaultIndent: '  ',modifyLineBreaks:textWrapOptions:columns:80" -m -w
      - name: Commit formatted LaTeX files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Format LaTeX files'
          file_pattern: '*.tex'
